name: RPM Build, SBOM, and Release

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag based on VERSION
        id: create_tag
        run: |
          TAG=$(cat ./VERSION)
          echo "TAG=$TAG" >> $GITHUB_ENV
        shell: bash

      - name: Run Docker Container
        run: docker run --privileged -d --name builder --network host rockylinux:9 /bin/sleep infinity

      - name: Install build tools RPM
        run: |
          docker cp ./ builder:/build
          docker exec builder bash -c "yum install -y epel-release && yum install -y make git mock"
          docker exec builder bash -c "rm -rf /etc/mock/default.cfg"

      - name: Setup SDK
        run: |
          docker exec builder bash -c "curl https://raw.githubusercontent.com/redBorder/repoinit/master/sdk9.cfg > /build/sdk9.cfg"
          docker exec builder bash -c "echo \"config_opts['use_host_resolv'] = True\" >> /build/sdk9.cfg"
          docker exec builder bash -c "ln -s /build/sdk9.cfg /etc/mock/default.cfg"

      - name: Build RPM using mock
        run: |
          docker exec builder bash -c "git config --global --add safe.directory /build"
          docker exec builder bash -c "cd /build/ && VERSION=${{ env.TAG }} make rpm"

      - name: Copy RPMS
        run: |
          docker cp builder:/build/packaging/rpm/pkgs/. ./rpms

      - name: Delete non-.rpm files
        run: |
          find ./rpms -type f -not -name '*.rpm' -exec rm {} \;

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM
        run: |
          syft scan dir:. --source-name redborder-monitor --source-version "${{ env.TAG }}" -o spdx-json=redborder-monitor-sbom.spdx.json

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Trivy
        run: |
          trivy sbom \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            redborder-monitor-sbom.spdx.json

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: |
            ./rpms/*
            redborder-monitor-sbom.spdx.json
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
